# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: New York City Subways Over Time
email: maxim.wilson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website displays various maps and cars in a custom timeline slideshow. Images were originally compiled and are properly archived on the MTA and nycsubway.org websites.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: maximwilson9
github_username:  maximwilson

# Build settings
markdown: kramdown
